[package]
name = "verify"
version = "0.1.0"
edition = "2021"

[dependencies]
patronus = { path = "../../patronus" }
clap = { version = "4.4.11", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
ctrlc = "3.4"
libc = "0.2"