[package]
name = "patronus"
version = "0.27.1"
description = "Hardware bug-finding toolkit."
homepage = "https://kevinlaeufer.com"
keywords = ["RTL", "btor", "model-checking", "SMT", "bit-vector"]
edition.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
indexmap = "2.0.0"
codespan-reporting = "0.11.1"
fuzzy-matcher = "0.3.7"
lazy_static = "1.4.0"
easy-smt = "0.2.1"
smallvec = { version = "1.x", features = ["union"] }
baa = "0.14.5"
boolean_expression = "0.4.4"
egg = "0.9.5"
rustc-hash = "2.0.0"
regex = "1.11.1"

[dev-dependencies]
clap =  { version = "4.4.8", features = ["derive"] }
insta = { version = "1.34.0", features = ["yaml"] }

